### ISSUE TITLE
[IDEA/PROPOSAL] add an input to allow for multiple dockerfiles

### ISSUE THREAD

**Issue by KudMath** [ripplr-io/docr-docker-publish#1]
In my case, I use a monorepo that'll have several Dockerfiles, it'd be nice to be able to specify which one to use in the action (and fallback to . if not provided) It doesn't feel like a lot of changes. 
I can submit a PR that does that.

**Comment by ggraca** [comment]
@KudMath absolutely! Feel free to submit the PR and new ideas for improvements.
